- name: Deploy openstack utility server
  hosts: openstack_utility
  become: True
  gather_facts: True
  tasks:
    - include_role:
        name: openstack
        tasks_from: common.yml
    - include_role:
        name: openstack
        tasks_from: utility.yml
    - name: disable services
      service:
        name: "{{item}}"
        state: stopped
        enabled: no
      with_items:
        - apache2
        - nova-api
        - nova-consoleauth
        - nova-scheduler
        - nova-conductor
        - nova-spiceproxy
        - neutron-server
        - neutron-linuxbridge-agent
        - neutron-metadata-agent
        - neutron-dhcp-agent
        - glance-api
        - glance-registry
        - haproxy
