- name: Deploy nova.conf and restart associated services on all control nodes
  hosts: openstack_compute_infrastructure
  user: root
  become: True
  tasks:
    - name: Deploy nova.conf
      template:
        src: roles/openstack/templates/control/nova.conf.j2
        dest: /etc/nova/nova.conf
        owner: nova
        group: nova
      notify:
        - restart nova-api
        - restart nova-conductor
        - restart nova-scheduler
        - restart nova-placement
  handlers:
    - name: restart nova-api
      service:
        name: nova-api
        state: restarted
    - name: restart nova-scheduler
      service:
        name: nova-scheduler
        state: restarted
    - name: restart nova-conductor
      service:
        name: nova-conductor
        state: restarted
    - name: restart nova-placement
      service:
        name: apache2
        state: restarted
- name: Deploy neutron.conf and restart associated services on all control nodes
  hosts: openstack_neutron
  user: root
  become: True
  tasks:
    - name: Deploy neutron.conf
      template:
        src: roles/openstack/templates/control/neutron.conf.j2
        dest: /etc/neutron/neutron.conf
        owner: neutron
        group: neutron
      notify:
        - restart neutron-server
        - restart neutron-dhcp-agent
        - restart neutron-metadata-agent
        - restart neutron-linuxbridge-agent
    - name: Deploy metadata_agent.ini
      template:
        src: roles/openstack/templates/control/metadata_agent.ini.j2
        dest: /etc/neutron/metadata_agent.ini
        owner: neutron
        group: neutron
      notify:
        - restart neutron-server
        - restart neutron-dhcp-agent
        - restart neutron-metadata-agent
        - restart neutron-linuxbridge-agent
    - name: Deploy linuxbridge_agent.ini
      template:
        src: roles/openstack/templates/control/linuxbridge_agent.ini.j2
        dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
        owner: neutron
        group: neutron
      notify:
        - restart neutron-server
        - restart neutron-dhcp-agent
        - restart neutron-metadata-agent
        - restart neutron-linuxbridge-agent
    - name: Deploy ml2.ini
      copy:
        src: roles/openstack/files/neutron/plugins/ml2/ml2_conf.ini
        dest: /etc/neutron/plugins/ml2/ml2_conf.ini
        owner: neutron
        group: neutron
      notify:
        - restart neutron-server
        - restart neutron-dhcp-agent
        - restart neutron-metadata-agent
        - restart neutron-linuxbridge-agent
  handlers:
    - name: restart neutron-server
      service:
        name: neutron-server
        state: restarted
    - name: restart neutron-dhcp-agent
      service:
        name: neutron-dhcp-agent
        state: restarted
    - name: restart neutron-metadata-agent
      service:
        name: neutron-metadata-agent
        state: restarted
    - name: restart neutron-linuxbridge-agent
      service:
        name: neutron-linuxbridge-agent
        state: restarted
